name: Pipeline Tests

on:
  push:
    branches:
      - main

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    # Checkout repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./main/requirements.txt

      # Run test script
      - name: Test the project
        run: |
          cd ./main/project
          ./test.sh
